In [2]:
import torch
import torch.nn as nn

In [3]:
#定义一个全连接层
linear = nn.Linear(5, 2)

In [4]:
# 1.常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [ ]:
#根据指定的值
nn.init.constant_(linear.weight, 0.5)
print(linear.weight)

Parameter containing:
tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]], requires_grad=True)


In [7]:
# 2.作eye初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [ ]:
# 3.正态分布初始化 
nn.init.normal_(linear.weight, mean=0, std=10)  #均值和方差
print(linear.weight)  

Parameter containing:
tensor([[ 7.0437, -1.0538,  7.9045, -5.4134, 14.8561],
        [-2.4540, -3.2650,  1.6242, 15.1840,  4.7850]], requires_grad=True)
