In [2]:
import torch
import torch.nn as nn

In [3]:
#定义一个全连接层
linear = nn.Linear(5, 2)

In [4]:
# 1.常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [5]:
#根据指定的值
nn.init.constant_(linear.weight, 0.5)
print(linear.weight)

Parameter containing:
tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]], requires_grad=True)


In [6]:
# 2.作eye初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [7]:
# 3.正态分布初始化 
nn.init.normal_(linear.weight, mean=0, std=10)  #均值和方差
print(linear.weight)  

Parameter containing:
tensor([[-14.3220,   6.4808,   3.2108,   2.6559,  18.3760],
        [  0.4362,  -5.6584,   4.5582,  16.8491,   5.5521]],
       requires_grad=True)


In [8]:
#4.均匀分布初始化
nn.init.uniform_(linear.weight, a=0, b=1)  #区间
print(linear.weight)

Parameter containing:
tensor([[0.0242, 0.8790, 0.3802, 0.3885, 0.2420],
        [0.8701, 0.8560, 0.9994, 0.5317, 0.5099]], requires_grad=True)


In [9]:
# 5. Xavier初始化
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.1521, -0.4707, -0.3422, -0.2817, -0.0979],
        [-0.1694,  0.3694, -0.0532, -0.9993, -0.1384]], requires_grad=True)


In [10]:
input = torch.randn(3, 5, device=torch.device('cuda'))
print(input.device)  

cuda:0
