In [1]:
import torch
import torch.nn as nn

In [11]:
#输入数据
input = torch.randn(3, 2) 
print(input)
pred = torch.sigmoid(input)  #经过sigmoid激活函数
print(pred)

tensor([[ 0.0718, -2.4813],
        [-1.2279, -0.5571],
        [-2.2970, -0.4726]])
tensor([[0.5179, 0.0772],
        [0.2266, 0.3642],
        [0.0914, 0.3840]])


In [12]:
#目标值
target = torch.tensor([[0, 1], [1, 0], [0, 1]], dtype=torch.float)
print(target)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [14]:
#定义损失函数
loss = nn.BCELoss()
print(loss(pred, target))

tensor(1.0470)
