In [15]:
import torch
import numpy as np

1.基本张量创建

(1)按内容创建张量 tensor

In [5]:
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10)
torch.Size([])
torch.int64


In [6]:
#传入一个一维数组
tensor2 = torch.tensor([1,2,3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([1, 2, 3])
torch.Size([3])
torch.int64


(2)按照维度创建张量 Tensor


In [13]:
tensor1 = torch.Tensor(2, 3, 4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([[[-3.9127e-34,  1.2359e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 3, 4])
torch.float32


In [16]:
tensor2 = torch.Tensor(np.ndarray([2,3,4])) #nan也是属于随机值
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., nan]]])
torch.Size([2, 3, 4])
torch.float32


(3)创建指定类型的张量

In [18]:
# int类型
tensor1 = torch.IntTensor(2, 3)
tensor2 = torch.tensor([1,2,3], dtype=torch.int)
print(tensor1.dtype)
print(tensor2.dtype)


torch.int32
torch.int32


In [19]:
# long类型
tensor1 = torch.LongTensor(2, 3)
tensor2 = torch.tensor([1,2,3], dtype=torch.long)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int64
torch.int64


In [20]:
# float类型
tensor1 = torch.FloatTensor(2, 3)
tensor2 = torch.tensor([1,2,3], dtype=torch.float)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float32
torch.float32


In [21]:
#bool类型
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([1,2,3], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)

torch.bool
torch.bool


6.3.2 创建指定区间的张量

In [22]:
tensor1 = torch.arange(0, 10, 2)
print(tensor1)

tensor([0, 2, 4, 6, 8])


In [24]:
tensor2 = torch.linspace(0, 10, 5)
print(tensor2)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


6.3.3创建指定数值的张量

In [25]:
tensor1 = torch.zeros(2, 3)
print(tensor1)
print(tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [26]:
tensor2 = torch.ones(2, 3)
print(tensor2)
print(tensor2.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [27]:
tensor3 = torch.full((2, 3), 10)
print(tensor3)
print(tensor3.dtype)

tensor([[10, 10, 10],
        [10, 10, 10]])
torch.int64


In [29]:
tensor4 = torch.eye(3, 3) #创建对角线为1其余元素为0的指定大小的矩阵
print(tensor4)
print(tensor4.dtype)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.float32


6.3.4 创建随机数张量

In [30]:
tensor1 = torch.rand(2, 3)
print(tensor1)
print(tensor1.dtype)

tensor([[0.0489, 0.9390, 0.3125],
        [0.3490, 0.5340, 0.6387]])
torch.float32


In [31]:
#创建指定范围之内的
tensor2 = torch.randint(0, 10, (2, 3))
print(tensor2)
print(tensor2.dtype)

tensor([[3, 2, 8],
        [2, 9, 1]])
torch.int64


In [32]:
#创建标准正态分布
tensor2 = torch.randn(2, 3)
print(tensor2)

tensor([[-0.6210, -0.0209, -1.1757],
        [-0.2783,  0.3307,  1.2450]])


In [33]:
# 创建自定义分布的张量
tensor2 = torch.rand(2, 3, generator=torch.Generator().manual_seed(42))
#
print(tensor2)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [37]:
#随机重新排列
tensor1 = torch.randperm(10) # 生成打乱后的索引，再拿去重排别的张量
print(tensor1)

tensor([2, 9, 3, 0, 5, 6, 1, 8, 4, 7])


In [67]:
#查看和指定随机数种子
print(torch.random.initial_seed())

42


In [ ]:
torch.manual_seed(42)