In [3]:
import torch
import numpy as np

6.4.1张量元素类型转换

In [4]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1.dtype)

torch.int64


In [8]:
#类型转换
tensor2 = tensor1.float()
print(tensor2.dtype)

#或者直接修改tensor1
tensor1 = tensor1.type(torch.float)
print(tensor1.dtype)

torch.float32
torch.float32


In [9]:
tensor1 = tensor1.half()
print(tensor1.dtype)

torch.float16


6.4.2 Tensor和ndarray转换

In [10]:
np.set_printoptions(precision=4)  #指定输出精度
torch.set_printoptions(precision=4)
#tensor -> ndarray
tensor1 = torch.rand(3, 4)
print(tensor1)

tensor([[0.2787, 0.3604, 0.0774, 0.1961],
        [0.9378, 0.9237, 0.8610, 0.0511],
        [0.7684, 0.7640, 0.8395, 0.4611]])


In [11]:
ndarray = tensor1.numpy()
print(ndarray)

[[0.2787 0.3604 0.0774 0.1961]
 [0.9378 0.9237 0.861  0.0511]
 [0.7684 0.764  0.8395 0.4611]]


In [12]:
tensor1[:, 0] = 10
print(tensor1)
print(ndarray)

tensor([[10.0000,  0.3604,  0.0774,  0.1961],
        [10.0000,  0.9237,  0.8610,  0.0511],
        [10.0000,  0.7640,  0.8395,  0.4611]])
[[10.      0.3604  0.0774  0.1961]
 [10.      0.9237  0.861   0.0511]
 [10.      0.764   0.8395  0.4611]]


In [15]:
#使用copy方法避免共享内存
array2 = tensor1.numpy().copy()
print(tensor1)
tensor1[:, 0] = 5
print(tensor1)
print(array2)

tensor([[1.0000e+02, 3.6045e-01, 7.7403e-02, 1.9606e-01],
        [1.0000e+02, 9.2372e-01, 8.6099e-01, 5.1104e-02],
        [1.0000e+02, 7.6399e-01, 8.3949e-01, 4.6113e-01]])
tensor([[5.0000, 0.3604, 0.0774, 0.1961],
        [5.0000, 0.9237, 0.8610, 0.0511],
        [5.0000, 0.7640, 0.8395, 0.4611]])
[[1.0000e+02 3.6045e-01 7.7403e-02 1.9606e-01]
 [1.0000e+02 9.2372e-01 8.6099e-01 5.1104e-02]
 [1.0000e+02 7.6399e-01 8.3949e-01 4.6113e-01]]


In [16]:
#2. ndarray -> tensor  还是一样使用copy可以避免共享内存
ndarray = np.random.rand(3, 4)
tensor1 = torch.from_numpy(ndarray)
print(tensor1)

tensor([[8.5003e-01, 4.9994e-04, 3.7109e-01, 9.8136e-01],
        [7.6273e-01, 8.2653e-01, 6.6275e-01, 2.4985e-01],
        [6.4015e-01, 4.0569e-01, 1.5372e-01, 5.2460e-01]], dtype=torch.float64)


6.4.3 Tensor和标量转换

In [17]:
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [18]:
print(tensor1.item()) #这是标量值，完全只是一个数

10
