In [2]:
import torch
import numpy as np

In [3]:
#1.四则运算  这个_，表示返回一个新的tensor
tensor1 = torch.randint(0, 10, (2, 3))
print(tensor1)

tensor([[0, 8, 9],
        [9, 4, 6]])


In [4]:
print(tensor1 + 1) #不会修改原始数据

tensor([[ 1,  9, 10],
        [10,  5,  7]])


In [5]:
print(tensor1.add(1)) #不会修改原始数据

tensor([[ 1,  9, 10],
        [10,  5,  7]])


In [6]:
print(tensor1)

tensor([[0, 8, 9],
        [9, 4, 6]])


In [9]:
#修改原始数据
tensor1.add_(10)
print(tensor1)

tensor([[ 1,  9, 10],
        [10,  5,  7]])


In [10]:
print(tensor1.sub_(1))

tensor([[0, 8, 9],
        [9, 4, 6]])


In [11]:
#幂函数
print(tensor1.pow_(2))

tensor([[ 0, 64, 81],
        [81, 16, 36]])


In [36]:
tensor1 = tensor1.float()
#开方运算
print(tensor1.sqrt_())

tensor([[0., 8., 9.],
        [9., 4., 6.]])


In [38]:
#计算张量的哈达玛积  对应位置相乘
tensor1 = torch.randint(0, 10, (2, 2))
print(tensor1)
tensor2 = torch.randint(0, 10, (2, 2))
print(tensor2)
print(tensor1 * tensor2)

tensor([[6, 8],
        [9, 7]])
tensor([[5, 6],
        [7, 4]])
tensor([[30, 48],
        [63, 28]])


In [39]:
print(tensor1.mul(tensor2))

tensor([[30, 48],
        [63, 28]])


In [40]:
#张量的矩阵乘法 matrix multiplication
tensor1 = torch.randint(0, 10, (2, 3))
print(tensor1)
tensor2 = torch.randint(0, 10, (3, 2))
print(tensor2)
print(tensor1.matmul(tensor2))

tensor([[1, 4, 6],
        [5, 9, 4]])
tensor([[4, 1],
        [6, 7],
        [1, 4]])
tensor([[34, 53],
        [78, 84]])


In [48]:
#验证内存的共享和节省内存
X = torch.randint(0, 10, (2, 3))
print(X)
print(id(X))

tensor([[5, 8, 0],
        [1, 8, 6]])
2589185019168


In [49]:
# X = X + 10  #X是指向了一个新的张量
X += 10

In [50]:
print(X)

tensor([[15, 18, 10],
        [11, 18, 16]])


In [51]:
print(id(X))

2589185019168


In [59]:
X = torch.randint(0, 10, (3, 2, 4))
Y = torch.randint(0, 10, (3, 4, 1))
print(X.shape)
print(id(X))
X @= Y  #如果后续X不再使用，可以使用X[:] = X @ Y来减少内存开销
print(X.shape)
print(id(X))

torch.Size([3, 2, 4])
2589185016368
torch.Size([3, 2, 1])
2589185020448
