In [1]:
import torch   #本章节介绍相应函数
import numpy as np

In [2]:
tensor1 = torch.randint(0, 10, (2, 5, 3))
print(tensor1)

tensor([[[2, 4, 3],
         [9, 2, 6],
         [4, 5, 4],
         [7, 4, 0],
         [8, 6, 1]],

        [[6, 9, 9],
         [2, 6, 3],
         [8, 5, 3],
         [6, 8, 1],
         [5, 9, 8]]])


In [3]:
#求和
print(tensor1.sum())

tensor(153)


In [5]:
print(tensor1.sum(dim=1))  #针对第一个维度对应元素求和

tensor([[30, 21, 14],
        [27, 37, 24]])


In [8]:
#mean求均值 必须是浮点数
print(tensor1.float().mean())
print(tensor1)

tensor(5.1000)
tensor([[[2, 4, 3],
         [9, 2, 6],
         [4, 5, 4],
         [7, 4, 0],
         [8, 6, 1]],

        [[6, 9, 9],
         [2, 6, 3],
         [8, 5, 3],
         [6, 8, 1],
         [5, 9, 8]]])


In [10]:
#求解标准方差
print(tensor1.float().std())

tensor(2.6826)


In [13]:
#求解最大值、最小值
print(tensor1.max(dim = 0))  #输出最大值 以及 对应索引号
print(tensor1.max(dim = 1))
print(tensor1.max(dim = 2))
print(tensor1.min())

torch.return_types.max(
values=tensor([[6, 9, 9],
        [9, 6, 6],
        [8, 5, 4],
        [7, 8, 1],
        [8, 9, 8]]),
indices=tensor([[1, 1, 1],
        [0, 1, 0],
        [1, 0, 0],
        [0, 1, 1],
        [0, 1, 1]]))
torch.return_types.max(
values=tensor([[9, 6, 6],
        [8, 9, 9]]),
indices=tensor([[1, 4, 1],
        [2, 0, 0]]))
torch.return_types.max(
values=tensor([[4, 9, 5, 7, 8],
        [9, 6, 8, 8, 9]]),
indices=tensor([[1, 0, 1, 0, 0],
        [1, 1, 0, 1, 1]]))
tensor(0)


In [16]:
print(tensor1.argmin())  #argmin / argmax 返回的是**“沿指定方向最小/最大值的下标”**，而不是值本身。
print(tensor1.argmax())

tensor(11)
tensor(3)


In [17]:
#去重
print(tensor1.unique())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [19]:
#排序 默认对于最后一个维度就是行进行排序
print(tensor1.sort())

torch.return_types.sort(
values=tensor([[[2, 3, 4],
         [2, 6, 9],
         [4, 4, 5],
         [0, 4, 7],
         [1, 6, 8]],

        [[6, 9, 9],
         [2, 3, 6],
         [3, 5, 8],
         [1, 6, 8],
         [5, 8, 9]]]),
indices=tensor([[[0, 2, 1],
         [1, 2, 0],
         [0, 2, 1],
         [2, 1, 0],
         [2, 1, 0]],

        [[0, 1, 2],
         [0, 2, 1],
         [2, 1, 0],
         [2, 0, 1],
         [0, 2, 1]]]))
