In [2]:
import torch

In [3]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[3, 9, 4, 1],
         [1, 3, 6, 2],
         [8, 6, 2, 8],
         [7, 9, 8, 4],
         [6, 7, 4, 2]],

        [[8, 5, 1, 8],
         [7, 6, 1, 7],
         [1, 8, 4, 1],
         [5, 9, 6, 7],
         [1, 3, 4, 5]],

        [[6, 3, 1, 8],
         [5, 1, 8, 8],
         [7, 7, 8, 6],
         [8, 5, 1, 3],
         [7, 6, 7, 2]]])


In [4]:
#1.简单索引
print(tensor1[0, 0, 1])

tensor(9)


In [5]:
print(tensor1[0, 1])

tensor([1, 3, 6, 2])


In [6]:
print(tensor1[0])

tensor([[3, 9, 4, 1],
        [1, 3, 6, 2],
        [8, 6, 2, 8],
        [7, 9, 8, 4],
        [6, 7, 4, 2]])


In [7]:
print(tensor1[1:])


tensor([[[8, 5, 1, 8],
         [7, 6, 1, 7],
         [1, 8, 4, 1],
         [5, 9, 6, 7],
         [1, 3, 4, 5]],

        [[6, 3, 1, 8],
         [5, 1, 8, 8],
         [7, 7, 8, 6],
         [8, 5, 1, 3],
         [7, 6, 7, 2]]])


In [8]:
# 列表索引
print(tensor1[[0, 1], [0, 1]]) #似乎明白了

tensor([[3, 9, 4, 1],
        [7, 6, 1, 7]])


In [9]:
print(tensor1[[0, 2], [0, 1], [2,1]])

tensor([4, 1])


In [13]:
#布尔索引
#选取符合条件的行，首元素大于5
mask = tensor1[:, :, 0] > 5
print(mask)

tensor([[False, False,  True,  True,  True],
        [ True,  True, False, False, False],
        [ True, False,  True,  True,  True]])


In [14]:
print(tensor1[mask])  #先取每行第一列的值 > 5 生成 True/False，再把 True 对应的整行抽出来

tensor([[8, 6, 2, 8],
        [7, 9, 8, 4],
        [6, 7, 4, 2],
        [8, 5, 1, 8],
        [7, 6, 1, 7],
        [6, 3, 1, 8],
        [7, 7, 8, 6],
        [8, 5, 1, 3],
        [7, 6, 7, 2]])


In [22]:
#选取符合条件的列，第二个元素大于5
mask = tensor1[:, 1, :] > 5
print(mask)

tensor([[False, False,  True, False],
        [ True,  True, False,  True],
        [False, False,  True,  True]])


In [24]:
# print(tensor1[mask])
# 需要转置
tensor2 = tensor1.mT  #把张量最后两个维度互换
print(tensor2[ mask])

tensor([[4, 6, 2, 8, 4],
        [8, 7, 1, 5, 1],
        [5, 6, 8, 9, 3],
        [8, 7, 1, 7, 5],
        [1, 8, 8, 1, 7],
        [8, 8, 6, 3, 2]])


In [28]:
#选取符合条件的矩阵
mask = tensor1[:, 1, 2] > 5
print(mask)
print(mask.shape)

tensor([ True, False,  True])
torch.Size([3])


In [26]:
print(tensor1[mask])  #mask必须保证前面的维度一致

tensor([[[3, 9, 4, 1],
         [1, 3, 6, 2],
         [8, 6, 2, 8],
         [7, 9, 8, 4],
         [6, 7, 4, 2]],

        [[6, 3, 1, 8],
         [5, 1, 8, 8],
         [7, 7, 8, 6],
         [8, 5, 1, 3],
         [7, 6, 7, 2]]])
