In [2]:
import torch

In [3]:
tensor1 = torch.randint(0, 10, (2, 3, 5))
print(tensor1)

tensor([[[0, 9, 3, 2, 2],
         [8, 0, 3, 5, 9],
         [4, 7, 0, 4, 9]],

        [[7, 9, 2, 8, 6],
         [2, 3, 3, 9, 9],
         [1, 9, 1, 7, 9]]])


6.8.1 交换维度

In [4]:
#交换维度
print(tensor1.transpose(0, 1))

tensor([[[0, 9, 3, 2, 2],
         [7, 9, 2, 8, 6]],

        [[8, 0, 3, 5, 9],
         [2, 3, 3, 9, 9]],

        [[4, 7, 0, 4, 9],
         [1, 9, 1, 7, 9]]])


In [5]:
print(tensor1.transpose(0, 2))  #交换维度理解似乎不够

tensor([[[0, 7],
         [8, 2],
         [4, 1]],

        [[9, 9],
         [0, 3],
         [7, 9]],

        [[3, 2],
         [3, 3],
         [0, 1]],

        [[2, 8],
         [5, 9],
         [4, 7]],

        [[2, 6],
         [9, 9],
         [9, 9]]])


In [7]:
# 重新排列多个维度
print(tensor1)
print(tensor1.permute(0, 2, 1))

tensor([[[0, 9, 3, 2, 2],
         [8, 0, 3, 5, 9],
         [4, 7, 0, 4, 9]],

        [[7, 9, 2, 8, 6],
         [2, 3, 3, 9, 9],
         [1, 9, 1, 7, 9]]])
tensor([[[0, 8, 4],
         [9, 0, 7],
         [3, 3, 0],
         [2, 5, 4],
         [2, 9, 9]],

        [[7, 2, 1],
         [9, 3, 9],
         [2, 3, 1],
         [8, 9, 7],
         [6, 9, 9]]])


6.8.2 调整形状 reshape 和 view 

In [ ]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

In [9]:
print(tensor1.reshape(3, -1))

tensor([[1, 8, 1, 3, 7, 6, 4, 3, 2, 2, 7, 3, 7, 8, 9, 8, 5, 9, 7, 4],
        [3, 9, 1, 7, 4, 1, 8, 1, 8, 9, 2, 4, 5, 1, 2, 4, 1, 7, 9, 3],
        [8, 5, 2, 1, 9, 7, 7, 5, 5, 1, 8, 6, 9, 6, 8, 7, 4, 7, 6, 7]])


In [10]:
print(tensor1.reshape(-1))

tensor([1, 8, 1, 3, 7, 6, 4, 3, 2, 2, 7, 3, 7, 8, 9, 8, 5, 9, 7, 4, 3, 9, 1, 7,
        4, 1, 8, 1, 8, 9, 2, 4, 5, 1, 2, 4, 1, 7, 9, 3, 8, 5, 2, 1, 9, 7, 7, 5,
        5, 1, 8, 6, 9, 6, 8, 7, 4, 7, 6, 7])


In [ ]:
#view
print(tensor1.is_contiguous()) #这玩意

True


In [15]:
print(tensor1.view(-1, 10))
print(tensor1.shape)
print(tensor1)

tensor([[1, 8, 1, 3, 7, 6, 4, 3, 2, 2],
        [7, 3, 7, 8, 9, 8, 5, 9, 7, 4],
        [3, 9, 1, 7, 4, 1, 8, 1, 8, 9],
        [2, 4, 5, 1, 2, 4, 1, 7, 9, 3],
        [8, 5, 2, 1, 9, 7, 7, 5, 5, 1],
        [8, 6, 9, 6, 8, 7, 4, 7, 6, 7]])
torch.Size([3, 5, 4])
tensor([[[1, 8, 1, 3],
         [7, 6, 4, 3],
         [2, 2, 7, 3],
         [7, 8, 9, 8],
         [5, 9, 7, 4]],

        [[3, 9, 1, 7],
         [4, 1, 8, 1],
         [8, 9, 2, 4],
         [5, 1, 2, 4],
         [1, 7, 9, 3]],

        [[8, 5, 2, 1],
         [9, 7, 7, 5],
         [5, 1, 8, 6],
         [9, 6, 8, 7],
         [4, 7, 6, 7]]])


In [16]:
tensor1 = tensor1.permute(2, 1, 0)
print(tensor1)

tensor([[[1, 3, 8],
         [7, 4, 9],
         [2, 8, 5],
         [7, 5, 9],
         [5, 1, 4]],

        [[8, 9, 5],
         [6, 1, 7],
         [2, 9, 1],
         [8, 1, 6],
         [9, 7, 7]],

        [[1, 1, 2],
         [4, 8, 7],
         [7, 2, 8],
         [9, 2, 8],
         [7, 9, 6]],

        [[3, 7, 1],
         [3, 1, 5],
         [3, 4, 6],
         [8, 4, 7],
         [4, 3, 7]]])


In [17]:
print(tensor1.is_contiguous())

False


In [19]:
print(tensor1.contiguous().view(-1))

tensor([1, 3, 8, 7, 4, 9, 2, 8, 5, 7, 5, 9, 5, 1, 4, 8, 9, 5, 6, 1, 7, 2, 9, 1,
        8, 1, 6, 9, 7, 7, 1, 1, 2, 4, 8, 7, 7, 2, 8, 9, 2, 8, 7, 9, 6, 3, 7, 1,
        3, 1, 5, 3, 4, 6, 8, 4, 7, 4, 3, 7])


6.8.3 增加或者删除维度

In [21]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1)

tensor([1, 2, 3])


In [ ]:
#在0维上增加一个矩阵
print(tensor1.unsqueeze(dim=0))   

tensor([[1, 2, 3]])


In [23]:
print(tensor1.unsqueeze(dim=1))

tensor([[1],
        [2],
        [3]])


In [24]:
tensor1 = torch.randint(1, 10, (3, 4))
print(tensor1)
print(tensor1.unsqueeze(dim = 2))


tensor([[3, 3, 1, 6],
        [5, 2, 4, 9],
        [2, 1, 4, 2]])
tensor([[[3],
         [3],
         [1],
         [6]],

        [[5],
         [2],
         [4],
         [9]],

        [[2],
         [1],
         [4],
         [2]]])


In [ ]:
#减少维度
print(tensor1)
print(tensor1.squeeze(dim = 0))
tensor2 = torch.randint(1, 10, (1, 2, 3))
print(tensor2) #只有指定维度为1维的时候，才可以缩减维度
print(tensor2.squeeze(dim = 0))   

tensor([[3, 3, 1, 6],
        [5, 2, 4, 9],
        [2, 1, 4, 2]])
tensor([[3, 3, 1, 6],
        [5, 2, 4, 9],
        [2, 1, 4, 2]])
tensor([[[8, 4, 8],
         [1, 2, 1]]])
tensor([[8, 4, 8],
        [1, 2, 1]])


6.9 张量拼接

In [ ]:
#拼接 是对应x维度的大小变大了
tensor1 = torch.randint(1, 10, (2, 3, 4))
tensor2 = torch.randint(1, 10, (2, 3, 4))
print(tensor1)
print(tensor2)

tensor([[[5, 6, 7, 8],
         [5, 5, 6, 7],
         [7, 9, 8, 4]],

        [[9, 6, 8, 6],
         [9, 4, 5, 2],
         [9, 4, 9, 9]]])
tensor([[[6, 3, 2, 2],
         [1, 9, 6, 1],
         [2, 7, 1, 3]],

        [[9, 9, 6, 8],
         [4, 1, 3, 6],
         [2, 6, 4, 4]]])


In [32]:
print(torch.cat((tensor1, tensor2), dim = 0)) #只改变拼接的维数  比如是dim=2，则最后dim1 + dim2

tensor([[[5, 6, 7, 8],
         [5, 5, 6, 7],
         [7, 9, 8, 4]],

        [[9, 6, 8, 6],
         [9, 4, 5, 2],
         [9, 4, 9, 9]],

        [[6, 3, 2, 2],
         [1, 9, 6, 1],
         [2, 7, 1, 3]],

        [[9, 9, 6, 8],
         [4, 1, 3, 6],
         [2, 6, 4, 4]]])


In [ ]:
#堆叠  是增加了一个总体维度，空间增加
tensor1 = torch.randint(1, 10, (2, 3, 4))
tensor2 = torch.randint(1, 10, (2, 3, 4))
print(tensor1)
print(tensor2)

tensor([[[9, 1, 8, 3],
         [7, 7, 4, 6],
         [8, 6, 8, 3]],

        [[1, 9, 9, 9],
         [6, 1, 4, 4],
         [7, 1, 5, 7]]])
tensor([[[9, 2, 7, 9],
         [7, 8, 9, 3],
         [1, 4, 3, 2]],

        [[9, 7, 4, 1],
         [8, 5, 4, 7],
         [1, 3, 3, 9]]])


In [35]:
tensor3 = torch.stack([tensor1, tensor2], dim = 0)
print(tensor3)
print(tensor3.shape)

tensor([[[[9, 1, 8, 3],
          [7, 7, 4, 6],
          [8, 6, 8, 3]],

         [[1, 9, 9, 9],
          [6, 1, 4, 4],
          [7, 1, 5, 7]]],


        [[[9, 2, 7, 9],
          [7, 8, 9, 3],
          [1, 4, 3, 2]],

         [[9, 7, 4, 1],
          [8, 5, 4, 7],
          [1, 3, 3, 9]]]])
torch.Size([2, 2, 3, 4])
