In [1]:
import torch

In [2]:
tensor1 = torch.randint(0, 10, (2, 3, 5))
print(tensor1)

tensor([[[5, 2, 0, 6, 9],
         [4, 1, 3, 4, 4],
         [2, 0, 0, 2, 1]],

        [[2, 9, 1, 4, 5],
         [2, 1, 7, 3, 1],
         [0, 6, 0, 9, 5]]])


6.8.1 交换维度

In [3]:
#交换维度
print(tensor1.transpose(0, 1))

tensor([[[5, 2, 0, 6, 9],
         [2, 9, 1, 4, 5]],

        [[4, 1, 3, 4, 4],
         [2, 1, 7, 3, 1]],

        [[2, 0, 0, 2, 1],
         [0, 6, 0, 9, 5]]])


In [4]:
print(tensor1.transpose(0, 2))  #交换维度理解似乎不够

tensor([[[5, 2],
         [4, 2],
         [2, 0]],

        [[2, 9],
         [1, 1],
         [0, 6]],

        [[0, 1],
         [3, 7],
         [0, 0]],

        [[6, 4],
         [4, 3],
         [2, 9]],

        [[9, 5],
         [4, 1],
         [1, 5]]])
