In [1]:
import torch

In [9]:
x = torch.tensor(2.0, requires_grad=True)
y = x.detach()
print(x)
print(y)

tensor(2., requires_grad=True)
tensor(2.)


In [3]:
print(id(x))
print(id(y))

1446124686624
1446124567872


In [ ]:
print(x.storage().data_ptr())
print(y.storage().data_ptr())    #其是共享内存中的同一份数据

3930230685888
3930230685888


In [ ]:
# print(x)
# y.zero_() #同时更改的
# print(x)

tensor(2., requires_grad=True)
tensor(0., requires_grad=True)


In [17]:
#分别对x和y进行后续计算
z1 = x ** 2
z2 = y ** 2
print('z1:', z1)
print('z2:', z2)

z1: tensor(4., grad_fn=<PowBackward0>)
z2: tensor(4.)


In [18]:
print(z1.requires_grad)
print(z2.requires_grad)

True
False


In [ ]:
z1.sum().backward()

In [ ]:
# z2.sum().backward()  #报错，因为y不需要梯度追踪，其计算图已经被切断

In [21]:
x = torch.ones(2, 2, requires_grad=True)
y = x * x
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [22]:
#分离y
u = y.detach()
print("U:", u)

U: tensor([[1., 1.],
        [1., 1.]])


In [23]:
#让u参与张量的计算
z = u * x
print("Z:", z)

Z: tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [ ]:
#反向传播，计算梯度
z.sum().backward()  #这里只是汇总标量，并没有损失维度
h = torch.ones_like(x) 
print(h)
print(h.sum()) #这是一个标量


tensor([[1., 1.],
        [1., 1.]])
tensor(4.)


In [25]:
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(x.grad == u) #将u参数当成常数来计算了

tensor([[True, True],
        [True, True]])
